### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by archienorman11** [beeper/linkedin-messaging-api#94]
```
    k: soup.find("input", {"name": k})["value"]
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10277ed10>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1023ac360>, 657348.902964083)]']
connector: <aiohttp.connector.TCPConnector object at 0x10277ed90>
```

Using the following example

https://github.com/beeper/linkedin-messaging-api/blob/master/examples/listen-for-events.py

**Comment by sumnerevans** [comment]
That login method probably doesn't work anymore. Try the manual login like this: https://github.com/beeper/linkedin-messaging-api/blob/master/examples/manual-login.py#L11-L14

Also, the examples are maintained as part of the project, if you have further problems, please ask them in the Matrix room.

**Comment by archienorman11** [comment]
@sumnerevans - can we open this issue as the matrix channel didnt seem to help much.

**Comment by sumnerevans** [comment]
I don't see any mention of this in the matrix room.

**Comment by archienorman11** [comment]
hi @sumnerevans , apologies, perhaps i posted in the wrong room, is the sdk room the correct place?

<img width="1139" alt="image" src="https://github.com/beeper/linkedin-messaging-api/assets/4103845/c99a3392-4771-4f1d-9905-ff63f82bdd8a">

**Comment by sumnerevans** [comment]
Oh, I remember that now. This isn't part of the supported Beeper SDK, so you probably are not going to get much help there. https://matrix.to/#/#linkedin-matrix:nevarro.space is the correct place.
